project:
  type: website

languages:
  en: 
    title: "Computation and Intelligence"
  es:
    title: "ComputaciÃ³n e Inteligencia"

website:
  title: "Computation and Intelligence"
  site-url: "https://sevisal.github.io/Computation_and_Intelligence/"
  favicon: "_resources/images/Icon.png?v=2"
  navbar:
    left:
      - text: "ğŸ  Home"
        href: index.html
      - text: "ğŸ”¬ Labs"
        menu:
          - text: "Lab 1"
            href: lab1.qmd
          # - text: "Lab 2"
          #   href: lab2.en.qmd
          # - text: "Lab 3"
          #   href: lab3.en.qmd
          # - text: "Lab 4"
          #   href: lab4.en.qmd
          # - text: "Lab 5"
          #   href: lab5.en.qmd
          # - text: "Lab 6"
          #   href: lab6.en.qmd
          # - text: "Lab 7"
          #   href: lab7.en.qmd
    right:
      - text: "ğŸŒ"
        href: "javascript:void(0)"
        id: lang-toggle

  page-footer:
    center: "Â© 2025 Carlos Sevilla Salcedo"

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: language.js
    relative_urls: true 
    page-layout: full
    toc: true
    toc-location: left
    toc-depth: 4
    page-navigation: true
    anchor-sections: true
    toc-title: "Contents"
    # Right margin for your cards
    grid:
      margin-width: 320px
      sidebar-width: 260px