project:
  type: website

website:
  title: "Computation and Intelligence"
  site-url: "https://sevisal.github.io/Computation_and_Intelligence/"
  navbar:
    left:
      - text: "ğŸ  Home"
        href: index.qmd
      - text: "Labs"
        menu:
          - text: "Lab 1"
            href: lab1.qmd
    right:
      - text: "ğŸŒ"
        href: "javascript:void(0)"

  page-footer:
    center: "Â© 2025 Carlos Sevilla Salcedo"

format:
  html:
    theme: cosmo
    css: styles.css
    include-after-body: lang.js
    relative_urls: true 
